kind: Deployment
apiVersion: apps/v1
metadata:
  name: consul-example-deployment
spec:
  selector:
    matchLabels:
      app: consul-discovery-service
  template:
    metadata:
      labels:
        app: consul-discovery-service
    spec:
      containers:
        - name: example
          image: consul:1.4.4
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
