apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul-discovery-service
  template:
    metadata:
      labels:
        app: consul-discovery-service
    spec:
      containers:
        - name: consul-pod
          image: consul:1.4.4
          imagePullPolicy: "IfNotPresent"
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          ports:
            - containerPort: 8500
---
apiVersion: v1
kind: Service
metadata:
  name: consul-service
spec:
  selector:
    app: consul-discovery-service
  ports:
    - port: 8500
      protocol: "TCP"
      targetPort: 8500
