spring:
  application:
    name: nasabah-api
  cloud:
    consul:
      discovery:
        enabled: true
        instance-id: ${spring.application.name}:${random.value}
      host: ${DISCOVERY_SERVICE_HOST:localhost}
      port: ${DISCOVERY_SERVICE_PORT:8500}
